### ISSUE TITLE
Errors reported by Xcode when loading project from skeleton branch

### ISSUE THREAD

**Issue by HoffmannKA** [AzureADQuickStarts/B2C-NativeClient-iOS#2] opened 2015-11-04 20:53 UTC
When I open the workspace for this demo, Xcode immediately displays two errors in SamplesSelectUserViewController.m.  The errors go away the first time the code is built, but I think the errors are pointing to a typo in the code.  Xcode is complaining about the two calls to acquireTokenSilentWithScopes:clientId:redirectUri:identifier:promptBehavior:completionBlock.  I think the problem is that these calls are passing in AD_CREDENTIALS_AUTO for the promptBehavior parameter.  I think the value that is supposed to be passed in is AD_PROMPT_AUTO.

**Comment by Jtango18** [comment] 2015-11-18 05:17
Hi HoffmannKA,

I've just submitted to @brandwe to resolve this issue. The promptBehavior parameter was deprecated in ADALiOS and recently removed. If you simply delete this parameter from the fund call you'll find it builds without problem.

Hope this helps.

Cheers

JT

**Comment by HoffmannKA** [comment] 2015-11-18 14:56
That "skeleton" branch of this repo includes a podfile.lock file which locks the project into a two-month old commit of ADAL.  The promptBehavior parameter hadn't been removed from the function definition in that version of ADAL.  I tried updating to the latest version of ADAL on the "convergence-dev" branch and removing the promptBehavior parameter from the calls.  I tried this two weeks ago, around the time I wrote up this issue.  I got passed the compilation problem, but the demo did not work with that version of ADAL.

**Comment by Jtango18** [comment] 2015-11-19 02:33
I've added a pull request to have to padlock file removed from skeleton as it shouldn't be committed. Are you able to
1. Re-clone the repo
2. Remove the padlock file
3. run 'pod install'
4. Confirm whether the issue is still present for you

I'd love to help you get to the bottom of this, but I'm unable to reproduce if I follow the above steps.

Cheers

JT

**Comment by derisen** [comment] 2023-06-02 16:44
Closing as this repo is being archived.

**Closed as completed by derisen** 2023-06-02 16:44 UTC
